all:
	make -C 86ADC; cp 86ADC\86ADC.exe ..
	make -C 86CLOCK; cp 86CLOCK\86CLOCK.exe ..
	make -C 86ComSh; cp 86ComSh\86ComSh.exe ..
	make -C 86CRSBAR; cp 86CRSBAR\86CRSBAR.exe ..
	make -C 86INFO; cp 86INFO\86INFO.exe ..
	make -C 86IO; cp 86IO\86IO.exe ..
	make -C 86PWM; cp 86PWM\86PWM.exe ..
	make -C 86UsbSh; cp 86UsbSh\86UsbSh.exe ..
	make -C CE_INIT; cp CE_INIT\CE_INIT.exe ..

clean: 
	make -C 86ADC clean
	make -C 86CLOCK clean
	make -C 86ComSh clean
	make -C 86CRSBAR clean
	make -C 86INFO clean
	make -C 86IO clean
	make -C 86PWM clean
	make -C 86UsbSh clean
	make -C CE_INIT clean