all:
	make -C Adafruit_CC3000
	make -C Adafruit_Motor_Shield
	make -C Audio
	make -C CANBus
	make -C CapacitiveSensor
	make -C EEPROM
	make -C Encoder
	make -C Ethernet
	make -C Firmata
	make -C FreeIMU1
	make -C GLCD
	make -C GSM
	make -C IRremote
	make -C LCD12864
	make -C LiquidCrystal
	make -C Mirf
	make -C MsTimer2
	make -C OneWire
	make -C RadioHead
	make -C RF12
	make -C RF24
	make -C Rosserial86
	make -C SD
	make -C Servo
	make -C Servo86
	make -C SoftwareSerial
	make -C SPI
	make -C SpiderL3S
	make -C Stepper
	make -C TFT
	make -C Time86
	make -C TimerOne
	make -C Tlc5940
	make -C USBHost
	make -C UTFT
	make -C UTouch
	make -C VirtualWire
	make -C WiFi
	make -C Wire

clean:
	make -C Adafruit_CC3000 clean
	make -C Adafruit_Motor_Shield clean
	make -C Audio clean
	make -C CANBus clean
	make -C CapacitiveSensor clean
	make -C EEPROM clean
	make -C Encoder clean
	make -C Ethernet clean
	make -C Firmata clean
	make -C FreeIMU1 clean
	make -C GLCD clean
	make -C GSM clean
	make -C IRremote clean
	make -C LCD12864 clean
	make -C LiquidCrystal clean
	make -C Mirf clean
	make -C MsTimer2 clean
	make -C OneWire clean
	make -C RadioHead clean
	make -C RF12 clean
	make -C RF24 clean
	make -C Rosserial86 clean
	make -C SD clean
	make -C Servo clean
	make -C Servo86 clean
	make -C SoftwareSerial clean
	make -C SPI clean
	make -C SpiderL3S clean
	make -C Stepper clean
	make -C TFT clean
	make -C Time86 clean
	make -C TimerOne clean
	make -C Tlc5940 clean
	make -C USBHost clean
	make -C UTFT clean
	make -C UTouch clean
	make -C VirtualWire clean
	make -C WiFi clean
	make -C Wire clean	
